name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: deno run -A jsr:@david/publish-on-tag@x.x.x
